envs:
  - aarch64-linux-22.04
  - x86_64-linux-20.04
apps:
  bat:
    type: cargo
    repo: sharkdp/bat
    version: 0.25.0
    tag: v{version}
    package: |
      mkdir -p $ARCHIVE_DIR/share/man/man1
      mkdir -p $ARCHIVE_DIR/share/bash-completion/completions
      cp target/$TARGET/release/build/bat-*/out/assets/manual/bat.1 $ARCHIVE_DIR/share/man/man1/bat.1 
      cp target/$TARGET/release/build/bat-*/out/assets/completions/bat.bash $ARCHIVE_DIR/share/bash-completion/completions/bat.bash
  delta:
    type: cargo
    repo: dandavison/delta
    version: 0.18.2
  fd:
    type: cargo
    repo: sharkdp/fd
    version: 10.2.0 
    tag: v{version}
    package: |
      mkdir -p $ARCHIVE_DIR/share/man/man1
      mkdir -p $ARCHIVE_DIR/share/bash-completion/completions
      make completions
      cp doc/fd.1 $ARCHIVE_DIR/share/man/man1/fd.1
      cp autocomplete/fd.bash $ARCHIVE_DIR/share/bash-completion/completions/fd.bash
  fzf:
    type: go
    repo: junegunn/fzf
    version: 0.54.1
    tag: v{version}
    package: |
      mkdir $ARCHIVE_DIR/share
      mkdir $ARCHIVE_DIR/shell
      cp -r man/ $ARCHIVE_DIR/share
      cp shell/completion.bash $ARCHIVE_DIR/shell/fzf.sh
  neovim:
    type: custom
    repo: neovim/neovim
    version: 0.10.2
    tag: v{version}
    exclude: ['aarch64-linux-22.04']
    package: |
      ./.github/scripts/install_deps.sh
      CMAKE_BUILD_TYPE=Release
      ./scripts/genappimage.sh
      cpack --config build/CPackConfig.cmake -G TGZ
      tar -xzf build/nvim-linux64.tar.gz -C $ARCHIVE_DIR --strip-components 1
  ripgrep:
    type: cargo
    repo: burntsushi/ripgrep
    version: 14.1.1
    exe_name: rg
    flags: --features=pcre2
    package: |
      cargo build
      bin="target/debug/rg"
      mkdir -p $ARCHIVE_DIR/share/man/man1
      mkdir -p $ARCHIVE_DIR/share/bash-completion/completions
      $bin --generate man > $ARCHIVE_DIR/share/man/man1/rg.1
      $bin --generate complete-bash > $ARCHIVE_DIR/share/bash-completion/completions/rg.bash
  selene:
    type: cargo
    repo: kampfkarren/selene
    version: 0.28.0
    flags: --no-default-features
  stylua:
    type: cargo
    repo: johnnymorganz/stylua
    version: 2.0.2
    tag: v{version}
  tmux:
    type: custom
    repo: tmux/tmux
    version: '3.3'
    exclude: ['aarch64-linux-22.04']
    package: |
      sudo apt install -y libevent-dev ncurses-dev build-essential bison \
        pkg-config autoconf automake
      sh autogen.sh
      ./configure
      make
      cp tmux $ARCHIVE_DIR/bin
      mkdir -p $ARCHIVE_DIR/share/man/man1
      cp tmux.1 $ARCHIVE_DIR/share/man/man1
  yq:
    type: go
    repo: mikefarah/yq
    version: 4.45.1
    tag: v{version}
    package: |
      sudo apt install pandoc -y
      mkdir -p $ARCHIVE_DIR/share/man/man1
      ./scripts/generate-man-page-md.sh
      pandoc --standalone --to man --variable=title:"YQ" \
            --variable=section:"1" \
            --variable=header:"yq (https://github.com/mikefarah/yq/) version $VERSION" \
            --variable=author:"Mike Farah" \
            --output=$ARCHIVE_DIR/share/man/man1/yq.1
  zoxide:
    type: cargo
    repo: ajeetdsouza/zoxide
    version: 0.9.7
    tag: v{version}
    package: |
      mkdir -p $ARCHIVE_DIR/share/bash-completion/completions 
      cp -r man/ $ARCHIVE_DIR/share
      cp contrib/completions/zoxide.bash $ARCHIVE_DIR/share/bash-completion/completions/zoxide.bash
